[build]
  command = "npm install --prefix client && npm run build --prefix client"
  publish = "client/build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[functions.timeout]
  default = 120

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
